// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzuzyjwhwliutqlvgymh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6dXp5andod2xpdXRxbHZneW1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDY4NjEsImV4cCI6MjA2OTc4Mjg2MX0.mmN5TVtirSyTY5qirPBBoiqu3D0ZyLL6ugM7Xum7sUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});